spring:
  application:
    name: demo
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/liveklass
    username: pick
    password: 1155
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    database-platform: org.hibernate.dialect.PostgreSQLDialect

settlement:
  fee-rate: 0.20
